# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: artur
email: arturweiss@ya.ru
description: > # this means to ignore newlines until "baseurl:"
  Eye-Catching Thumbnail Designer.


#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://artur.ga" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: artur

copyright:
   name: artur
   year: "2022"
   link: 'http://artur.ga'

# Build settings
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics:

# Comments
disqus: yes
disqus-shortname: artur-7

#social
facebook:
quora:
twitter:
email: arturweiss@ya.ru

#facebook like box
fb-like-box: no
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
