---
title: artur
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: arturweiss@ya.ru
description: 'Eye-Catching Thumbnail Designer.

'
url: https://artur.ga
default-image: webjeda-logo-big.jpg
built-by: artur
copyright:
  name: artur
  year: '2022'
  link: http://artur.ga
permalink: "/:title/"
paginate: 9
paginate_path: "/page:num/"
analytics: 
disqus: true
disqus-shortname: artur-7
facebook: 
quora: 
twitter: design_artur
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-seo-tag
